AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.audioSplitter::AudioSplitter
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AudioSplitterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.audioSplitter.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/AudioSplitter-0.0.1-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AudioSplitterApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AudioSplitterApi
